spring:
  datasource:
    url: ${PSQL_DB_URL}
    username: ${PSQL_DB_USR}
    password: ${PSQL_DB_PASS}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${APPLICATION_PORT}
